### PR TITLE
Merge from integration_2023-08-02_11.47 to main (Cray-HPE/prodmgr) 08-02

### PR DESCRIPTION
**Pull request by haasken-hpe**
CRAYSAT-1219 Allow arbitrary podman arguments to prodmgr (#18)

### CODE REVIEW

**Review by sravani-sanigepalli — APPROVED** [review]

**Comment by haasken-hpe** [comment]
Thank you for the review @sravani-sanigepalli. I would like to delete the integration branch in this repository and switch to instead using `main` as the default branch. The `integration` branch is sort of a relic of the past. In a previous product, we used to do integration testing across the whole product by using the integration branch of every component. We are not doing anything like that here, so this really just adds an extra step.

Do you have any objections to me removing the `integration` branch and changing the default branch to `main`?

I would also like to consider using tags for releases. I will let you know about that. I'm working on this in [CRAYSAT-1754](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1754) since this repo originated from the SAT team.

**Comment by haasken-hpe** [comment]
@sravani-sanigepalli, since the `integration` branch was simply behind the `main` branch now, I just went ahead and deleted the `integration` branch and made `main` the default branch for this repository. You shouldn't need to do anything to your existing branches in this repository which were based off integration, but if you want, you can rebase them on the latest `main` branch. Any future PRs can be made directly to the `main` branch. Let me know if you run into any issues. Thanks!

**Comment by haasken-hpe** [comment]
Also FYI, @jsollom-hpe and @sravani-sanigepalli, I did go ahead and create the `release/1.2` branch for this repository to get a stable build of the prodmgr RPM. You can find that here in artifactory:

https://artifactory.algol60.net/ui/repos/tree/General/csm-rpms/hpe/stable/sle-15sp4/cray-prodmgr/x86_64/cray-prodmgr-1.2.1-1.x86_64.rpm

In this repo, builds off the `release/*` branches go to that stable repository. Builds off of `main` go to an unstable repository in Artifactory. We may switch to tags in the near future, but I wanted to make sure we had a stable build with the changes to use `product-deletion-utility` for now.

**Comment by sravani-sanigepalli** [comment]
> Also FYI, @jsollom-hpe and @sravani-sanigepalli, I did go ahead and create the `release/1.2` branch for this repository to get a stable build of the prodmgr RPM. You can find that here in artifactory:
> 
> https://artifactory.algol60.net/ui/repos/tree/General/csm-rpms/hpe/stable/sle-15sp4/cray-prodmgr/x86_64/cray-prodmgr-1.2.1-1.x86_64.rpm
> 
> In this repo, builds off the `release/*` branches go to that stable repository. Builds off of `main` go to an unstable repository in Artifactory. We may switch to tags in the near future, but I wanted to make sure we had a stable build with the changes to use `product-deletion-utility` for now.

Sure. This should work for now. Thanks @haasken-hpe

**Pull request merged**
